version: '2'
services:
  crawler:
    build: ./crawler
    links:
      - parser_package_tracking
      - indexer
    environment:
      IMAP_URL: my.iamthefij.com
      IMAP_USER: iamthefij@iamthefij.com
      IMAP_PASS: "${IMAP_PASS}"
      INDEXER: http://indexer:5000
      PARSER_1: http://parser_package_tracking:3000
  indexer:
    build: ./indexer
    ports:
      - "8181:5000"
  parser_package_tracking:
    build: ./parsers/package-tracking
    ports:
      - "8183:3000"
  viewer_main:
    build: ./viewers/main
    volumes:
      - ./viewers/main:/usr/src/app
    links:
      - indexer
      - viewer_package_tracking
    environment:
      INDEXER_URL: http://indexer:5000
    ports:
      - "8184:5000"
  viewer_package_tracking:
    build: ./viewers/package-tracking
    environment:
      UPS_KEY: ${UPS_KEY}
      UPS_USER_ID: ${UPS_USER_ID}
      UPS_PASSWORD: ${UPS_PASSWORD}
    ports:
      - "8185:3000"
