version: '2'
services:
  main:
    build: .
    volumes:
      - .:/src
    environment:
      UPS_KEY: ${UPS_KEY}
      UPS_USER_ID: ${UPS_USER_ID}
      UPS_PASSWORD: ${UPS_PASSWORD}
    ports:
      - "8185:3000"
